import { Job, Worker } from '../types';

export const jobs: Job[] = [
  {
    id: 'job-1',
    company: 'Astra Precision Components',
    area: 'Jeedimetla',
    role: 'Production Supervisor',
    shift: 'Rotational',
    pay: '₹28k–₹40k',
    skills: ['Line balancing', 'OEE', 'Team handling'],
  },
  {
    id: 'job-2',
    company: 'Delta Aero Systems',
    area: 'Adibatla',
    role: 'Automation Engineer',
    shift: 'General',
    pay: '₹45k–₹70k',
    skills: ['PLC', 'SCADA', 'Sensors'],
  },
  {
    id: 'job-3',
    company: 'Nova Fabrication Works',
    area: 'Patancheru',
    role: 'Welding Technician',
    shift: 'Night',
    pay: '₹20k–₹32k',
    skills: ['MIG', 'TIG', 'Fabrication drawings'],
  },
  {
    id: 'job-4',
    company: 'Metro Bearing Tech',
    area: 'Balanagar',
    role: 'Quality Control (QC) Engineer',
    shift: 'General',
    pay: '₹30k–₹48k',
    skills: ['SPC', 'Root cause', 'Calibration'],
  },
  {
    id: 'job-5',
    company: 'Skylink Manufacturing',
    area: 'Cherlapally',
    role: 'Plant Head / Factory Head',
    shift: 'General',
    pay: '₹1.8L–₹2.6L',
    skills: ['Operations strategy', 'P&L', 'Team leadership'],
  },
];

export const workers: Worker[] = [
  {
    id: 'worker-1',
    name: 'Ravi Kumar',
    area: 'Cherlapally',
    role: 'Maintenance Technician',
    experience: '5 years',
    shift: 'Any',
    salaryPreference: '₹26k+',
    skills: ['Preventive maintenance', 'Breakdown handling', 'Motors'],
    certifications: ['Safety training'],
    availableNow: true,
  },
  {
    id: 'worker-2',
    name: 'Sneha Reddy',
    area: 'Genome Valley',
    role: 'Quality Assurance (QA) Engineer',
    experience: '4 years',
    shift: 'General',
    salaryPreference: '₹35k+',
    skills: ['CAPA', 'Audit', 'Documentation'],
    certifications: ['ISO internal auditor'],
    availableNow: true,
  },
  {
    id: 'worker-3',
    name: 'Mahesh Yadav',
    area: 'IDA Bollaram',
    role: 'Machine Operator (CNC, Lathe, Milling)',
    experience: '6 years',
    shift: 'Rotational',
    salaryPreference: '₹30k+',
    skills: ['Fanuc', 'Tool offset', 'Quality checks'],
    certifications: ['CNC machining'],
    availableNow: false,
  },
  {
    id: 'worker-4',
    name: 'Anitha Verma',
    area: 'Jeedimetla',
    role: 'Production Supervisor',
    experience: '8 years',
    shift: 'General',
    salaryPreference: '₹42k+',
    skills: ['Daily production planning', 'Shift control', 'KPI reporting'],
    certifications: ['Lean basics'],
    availableNow: true,
  },
];
