export const roleCategories = {
  leadership: [
    'Plant Head / Factory Head',
    'General Manager – Manufacturing',
    'Operations Head',
    'Unit Head',
    'Works Manager',
    'Production Head',
    'Technical Director',
    'Manufacturing Head',
  ],
  production: [
    'Production Manager',
    'Production Supervisor',
    'Shift In-Charge',
    'Line Leader / Line Supervisor',
    'Machine Operator (CNC, Lathe, Milling)',
    'Assembly Technician',
    'Fabrication Technician',
    'Welding Technician',
    'Shop Floor Executive',
  ],
  engineering: [
    'Mechanical Engineer',
    'Electrical Engineer',
    'Electronics Engineer',
    'Maintenance Engineer',
    'Automation Engineer',
    'Tool & Die Engineer',
    'Process Engineer',
    'Industrial Engineer',
  ],
  design: [
    'Design Engineer (CAD/CAM)',
    'R&D Engineer',
    'Product Development Engineer',
    'Drafting Engineer / Design Draftsman',
    'Tool Design Engineer',
    'Simulation Engineer (CAE)',
  ],
  quality: [
    'Quality Control (QC) Engineer',
    'Quality Assurance (QA) Engineer',
    'Quality Inspector',
    'Testing Engineer',
    'Calibration Engineer',
    'Six Sigma / Lean Engineer',
  ],
  maintenance: [
    'Maintenance Manager',
    'Maintenance Technician',
    'Electrical Maintenance Engineer',
    'Utility Engineer (Boilers, HVAC, etc.)',
    'Instrumentation Engineer',
  ],
  supplyChain: [
    'Store Manager',
    'Inventory Controller',
    'Purchase Executive',
    'Procurement Manager',
    'Warehouse Executive',
    'Logistics Coordinator',
  ],
  planning: [
    'Production Planning Engineer (PPC)',
    'MIS Executive',
    'ERP Executive (SAP/Oracle/Tally)',
    'Demand Planner',
  ],
  skilled: [
    'CNC Operator',
    'Turner / Fitter',
    'Machinist',
    'Welder',
    'Electrician (Industrial)',
    'Tool Room Technician',
    'Injection Molding Operator',
  ],
  support: [
    'EHS Officer (Environment, Health & Safety)',
    'HR Executive (Factory HR)',
    'Compliance Officer',
    'Admin Executive',
  ],
};

export const allRoles = Object.values(roleCategories).flat();

export const mostDemandingRoles = [
  'Production Supervisor',
  'Machine Operator (CNC, Lathe, Milling)',
  'Quality Control (QC) Engineer',
  'Maintenance Technician',
  'Automation Engineer',
];
