/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/factory` | `/factory`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/jobs` | `/jobs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/talent` | `/talent`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/auth/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/factory/pipeline`; params?: Router.UnknownInputParams; } | { pathname: `/worker/applications`; params?: Router.UnknownInputParams; } | { pathname: `/worker/saved`; params?: Router.UnknownInputParams; } | { pathname: `/jobs/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/factory` | `/factory`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/jobs` | `/jobs`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/talent` | `/talent`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/factory/pipeline`; params?: Router.UnknownOutputParams; } | { pathname: `/worker/applications`; params?: Router.UnknownOutputParams; } | { pathname: `/worker/saved`; params?: Router.UnknownOutputParams; } | { pathname: `/jobs/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/factory${`?${string}` | `#${string}` | ''}` | `/factory${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/jobs${`?${string}` | `#${string}` | ''}` | `/jobs${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/talent${`?${string}` | `#${string}` | ''}` | `/talent${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/signup${`?${string}` | `#${string}` | ''}` | `/auth/welcome${`?${string}` | `#${string}` | ''}` | `/factory/pipeline${`?${string}` | `#${string}` | ''}` | `/worker/applications${`?${string}` | `#${string}` | ''}` | `/worker/saved${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/factory` | `/factory`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/jobs` | `/jobs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/talent` | `/talent`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/auth/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/factory/pipeline`; params?: Router.UnknownInputParams; } | { pathname: `/worker/applications`; params?: Router.UnknownInputParams; } | { pathname: `/worker/saved`; params?: Router.UnknownInputParams; } | `/jobs/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/jobs/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
